
library(Seurat)
library(dplyr)
library(tidyverse)
library(Matrix)
library(ggplot2)
library(ggsci)
library(scRepertoire)
library(Biostrings)
library(ggpubr)
library(ggrepel)
library(patchwork)
library(cowplot)


options(bitmapType='cairo')


## to calculate rowratio for a matrix
#
rowRatio <- function(df){
  for(i in 1:dim(df)[1]){
    df[i,] <- df[i,]/rowSums(df)[i]
  }
  return(df)
}


## sinature score
# as calculated in Dianyu's github               
# https://github.com/chendianyu/2021_NI_scGCB/blob/main/script/Signature_score.Rmd 

## The code below is from Adam Hamber
## 2D scoring by Itay
get_controls <- function(counts, gene.list, verbose=F, control.genes.per.gene=10)
{
  # Itay: "Such scores are inevitably correlated with cell complexity so to avoid 
  # that I subtract a "control" score which is generated by averaging over a control 
  # gene set. Control gene sets are chosen to contain 100 times more genes than the 
  # real gene set (analogous to averaging over 100 control sets of similar size) and 
  # to have the same distribution of population/bulk - based expression levels as the 
  # real gene set, such that they are expected to have the same number of "zeros" and 
  # to eliminate the correlation with complexity."
  # ---------------------------------------------------------------------------------
  # Going to find control points by finding the closest genes in terms of expression level and % of the time we observe it
  if(verbose){cat(sprintf("Finding %s background genes based on similarity to given gene set [%s genes] \n", 
                          control.genes.per.gene*length(gene.list), length(gene.list)))}
  cat("Summarizing data \n")
  summary = data.frame(gene=row.names(counts), mean.expr = Matrix::rowMeans(counts), fract.zero = Matrix::rowMeans(counts==0), stringsAsFactors = F)
  #summary = data.frame(gene=row.names(counts), mean.expr = apply(counts,1,mean), fract.zero = apply(counts==0,1,mean), stringsAsFactors = F)
  summary$mean.expr.s = scale(summary$mean.expr)
  summary$fract.zero.s = scale(summary$fract.zero)
  actual.genes = summary[summary$gene %in% gene.list,]
  background.genes = summary[!summary$gene %in% gene.list,]
  
  #find the 10 closest genes to each cell cycle marker gene and add them to the lists of control genes
  get_closest_genes <- function(i)
  {
    background.genes$dist = sqrt((background.genes$mean.expr.s - actual.genes$mean.expr.s[i])^2 + 
                                   (background.genes$fract.zero.s - actual.genes$fract.zero.s[i])^2)
    ordered = background.genes$gene[order(background.genes$dist)]
    ordered = ordered[!ordered %in% controls] # don't take genes that already appear in the list 
    closest = head(ordered, n=control.genes.per.gene)
    return(closest)
  }
  controls = c();
  
  for (i in 1:length(gene.list)){
    #info(sprintf("Finding %s control genes for %s", control.genes.per.gene, gene.list[i]))
    closest = get_closest_genes(i)
    #info(sprintf("Found %s: ", length(closest)))
    controls = unique(c(controls, closest))
  }
  
  if(verbose){cat(sprintf("Control gene selection complete. %s genes found. \n", length(controls)))}
  #print(controls)
  return(controls)
}


calculate_signature_score <- function(count_matrix, gene_list){
  control_gene <- get_controls(counts = count_matrix,
                               gene.list = gene_list)
  signature_score <- colMeans(count_matrix[gene_list, ], na.rm = TRUE) - 
    colMeans(count_matrix[control_gene, ], na.rm = TRUE)
  return(signature_score)
}


add_geneset_score <- function(obj, geneset, setname, Assay="RNA"){
  score <- calculate_signature_score(as.data.frame(obj@assays[[Assay]]@data),
                                     geneset)
  obj <- AddMetaData(obj,
                     score,
                     setname)
  return(obj)
}



color.test <- colorRampPalette(
  c(
    "#03047F", # deep blue
    "white",
    "#CC2627"  # deep red
  )
)(100)












